### ISSUE TITLE
PersistentInto for T is Failing with mysql::Pool

### ISSUE THREAD

**Issue by TheServerAsterisk** [iron/persistent#63]
I get the following output when trying to persist the mysql::Pool struct. 

```rust
error[E0277]: the trait bound `mysql::conn::pool::Pool: persistent::PersistentInto<std::sync::Arc<mysql::Pool>>` is not satisfied
  --> src/bin/bin.rs:70:23
   |
70 |     chain.link_before(Read::<DBKey>::one(pool));
   |                       ^^^^^^^^^^^^^^^^^^ trait `mysql::conn::pool::Pool: persistent::PersistentInto<std::sync::Arc<mysql::Pool>>` not satisfied
   |
   = note: required by `<persistent::Read<P>>::one`
```

I thought it might be due a mismatched dependency so I forked the and set the iron dependency to 0.5.1 (which is what I am using), but this didn't work as well. Any ideas on how to resolve this?

**Comment by untitaker** [comment]
You're using the wrong version of Iron together with persistent. If you use persistent 0.3, you need Iron 0.5. If you use persistent 0.2, you need Iron 0.4
